package com.paytm.pgplus.upipsphandler.enums;

public enum SystemResponseCode {
    DEFAULT_FAILURE_CODE("DEFAULT_FAILURE_CODE"), DEFAULT_PENDING_CODE("DEFAULT_PENDING_CODE"), DEFAULT_SUCCESS_CODE(
            "DEFAULT_SUCCESS_CODE"), PAGE_OPEN_RESPONSE_CODE("PAGE_OPEN_RESPONSE_CODE"), POLL_PAGE_ABANDONED_CODE(
            "POLL_PAGE_ABANDONED_CODE"), USER_CLOSED_RESPONSE_CODE("USER_CLOSED_RESPONSE_CODE"), CHECKSUM_FAILURE_CODE(
            "CHECKSUM_FAILURE_CODE"), SC_INTERNAL_SERVER_ERROR("SC_INTERNAL_SERVER_ERROR"), ABANDON_AT_BANK_PAGE(
            "ABANDON_AT_BANK_PAGE"), ABANDON_AT_CASHIER_PAGE("ABANDON_AT_CASHIER_PAGE"), PARAM_MISSING("PARAM_MISSING"), PARAM_ILLEGAL(
            "PARAM_ILLEGAL"), INVALID_SIGNATURE("INVALID_SIGNATURE"), KEY_NO_FOUND("KEY_NO_FOUND"), NO_INTERFACE_DEF(
            "NO_INTERFACE_DEF"), API_IS_INVALID("API_IS_INVALID"), MSG_PARSE_ERROR("MSG_PARSE_ERROR"), OAUTH_FAILED(
            "OAUTH_FAILED"), FUNCTION_NOT_MATCH("FUNCTION_NOT_MATCH"), SYSTEM_ERROR("SYSTEM_ERROR"), VERIFY_CLIENT_SECRET_FAIL(
            "VERIFY_CLIENT_SECRET_FAIL"), CLIENT_FORBIDDEN_ACCESS_API("CLIENT_FORBIDDEN_ACCESS_API"), UNAUTH_API_FLOW_ACCESS(
            "UNAUTH_API_FLOW_ACCESS"), UNKNOWN_CLIENT("UNKNOWN_CLIENT"), INVALID_CLIENT_STATUS("INVALID_CLIENT_STATUS"), MERCHANT_BLOCKED(
            "MERCHANT_BLOCKED"), MERCHANT_BLOCKED_PAYMENT("MERCHANT_BLOCKED_PAYMENT"), ACCOUNT_NUMBER_MISMATCH(
            "ACCOUNT_NUMBER_MISMATCH"), ACCOUNT_NUMBER_NOT_EXIST("ACCOUNT_NUMBER_NOT_EXIST"), INVALID_REQUEST(
            "INVALID_REQUEST"), SUCCESS_IDEMPOTENT_ERROR("SUCCESS_IDEMPOTENT_ERROR"), ACCESS_DENIED("ACCESS_DENIED"), AMOUNT_EXCEEDS_LIMIT(
            "AMOUNT_EXCEEDS_LIMIT"), USER_NOT_EXISTS("USER_NOT_EXISTS"), MERCHANT_NOT_EXIST("MERCHANT_NOT_EXIST"), USER_STATUS_ABNORMAL(
            "USER_STATUS_ABNORMAL"), REPEAT_REQ_INCONSISTENT("REPEAT_REQ_INCONSISTENT"), RISK_REJECT("RISK_REJECT"), MERCHANT_RISK_REJECT(
            "MERCHANT_RISK_REJECT"), ORDER_STATUS_INVALID("ORDER_STATUS_INVALID"), PROCESS_FAIL("PROCESS_FAIL"), INVALID_OFFLINE_REQUEST(
            "INVALID_OFFLINE_REQUEST"), TRANS_STATUS_ABNORMAL("TRANS_STATUS_ABNORMAL"), BALANCE_ACCOUNT_NOT_EXIST(
            "BALANCE_ACCOUNT_NOT_EXIST"), PAYER_STATUS_ABNORMAL("PAYER_STATUS_ABNORMAL"), MERCHANT_STATUS_DISABLE(
            "MERCHANT_STATUS_DISABLE"), KYC_VALIDATION_REQUIRED("KYC_VALIDATION_REQUIRED"), PAYEE_USER_NOT_EXIST_TOPUP(
            "PAYEE_USER_NOT_EXIST_TOPUP"), PAYEE_USER_STATUS_DISABLE_TOPUP("PAYEE_USER_STATUS_DISABLE_TOPUP"), PAYEE_ACCOUNT_NOT_EXIST_TOPUP(
            "PAYEE_ACCOUNT_NOT_EXIST_TOPUP"), PAYEE_TYPE_ILLEGAL_TOPUP("PAYEE_TYPE_ILLEGAL_TOPUP"), ACCOUNT_IN_DISABLE_TOPUP(
            "ACCOUNT_IN_DISABLE_TOPUP"), EXCEED_KYC_BALANCE_LIMIT_TOPUP("EXCEED_KYC_BALANCE_LIMIT_TOPUP"), EXCEED_NON_KYC_BALANCE_LIMIT_TOPUP(
            "EXCEED_NON_KYC_BALANCE_LIMIT_TOPUP"), AMOUNT_LESS_THAN_MIN_LIMIT_TOPUP("AMOUNT_LESS_THAN_MIN_LIMIT_TOPUP"), AMOUNT_EXCEED_SINGLE_LIMIT_TOPUP(
            "AMOUNT_EXCEED_SINGLE_LIMIT_TOPUP"), PAYEE_AMOUNT_EXCEED_DAILY_LIMIT_TOPUP(
            "PAYEE_AMOUNT_EXCEED_DAILY_LIMIT_TOPUP"), PAYEE_AMOUNT_EXCEED_MONTH_LIMIT_TOPUP(
            "PAYEE_AMOUNT_EXCEED_MONTH_LIMIT_TOPUP"), PAYEE_AMOUNT_EXCEED_YEAR_LIMIT_TOPUP(
            "PAYEE_AMOUNT_EXCEED_YEAR_LIMIT_TOPUP"), REPEAT_REQ_INCONSISTENT_TOPUP("REPEAT_REQ_INCONSISTENT_TOPUP"), BALANCE_NOT_ENOUGH_CREATE_PAY(
            "BALANCE_NOT_ENOUGH_CREATE_PAY"), PAY_AMOUNT_UNEQUAL_ORDER_AMOUNT("PAY_AMOUNT_UNEQUAL_ORDER_AMOUNT"), EXCEEDS_CHANNEL_LIMIT(
            "EXCEEDS_CHANNEL_LIMIT"), CHANNEL_STATUS_NOT_ENABLE("CHANNEL_STATUS_NOT_ENABLE"), NEED_RISK_CHALLENGE(
            "NEED_RISK_CHALLENGE"), DUPLICATE_PAYMENT_REQUEST("DUPLICATE_PAYMENT_REQUEST"), UNSUPPORT_ISSUING_COUNTRY(
            "UNSUPPORT_ISSUING_COUNTRY"), ORDER_NOT_EXISTS("ORDER_NOT_EXISTS"), ORDER_IS_CLOSED("ORDER_IS_CLOSED"), ORDER_IS_FROZEN(
            "ORDER_IS_FROZEN"), ORDER_IS_PAID("ORDER_IS_PAID"), FUND_ORDER_STATUS_INVALID("FUND_ORDER_STATUS_INVALID"), FEE_RATE_NOT_EXIST(
            "FEE_RATE_NOT_EXIST"), FEE_RATE_NOT_MATCH("FEE_RATE_NOT_MATCH"), TARGET_NOT_FOUND("TARGET_NOT_FOUND"), CARD_INDEX_NO_NOT_EXIST(
            "CARD_INDEX_NO_NOT_EXIST"), SESSION_EXPIRY("SESSION_EXPIRY"), CHANNEL_NOT_AVAILABLE("CHANNEL_NOT_AVAILABLE"), CHANNEL_NOT_IN_SERVICE_TIME(
            "CHANNEL_NOT_IN_SERVICE_TIME"), CHANNEL_UNDER_MAINTENANCE("CHANNEL_UNDER_MAINTENANCE"), EXCEED_CHANNEL_AMOUNT_LIMIT(
            "EXCEED_CHANNEL_AMOUNT_LIMIT"), BALANCE_NOT_ENOUGH_PAY("BALANCE_NOT_ENOUGH_PAY"), DUPLICATE_REQUEST(
            "DUPLICATE_REQUEST"), PAYMENT_AMOUNT_UNMATCH("PAYMENT_AMOUNT_UNMATCH"), RISK_VERIFICATION(
            "RISK_VERIFICATION"), PAYEE_STATUS_ABNORMAL("PAYEE_STATUS_ABNORMAL"), PAYER_MOBILE_NOT_VERIFY(
            "PAYER_MOBILE_NOT_VERIFY"), PAYEE_MOBILE_NOT_VERIFY("PAYEE_MOBILE_NOT_VERIFY"), PAYER_USER_NOT_KYC(
            "PAYER_USER_NOT_KYC"), PAYEE_USER_NOT_KYC("PAYEE_USER_NOT_KYC"), ACCOUNT_OUT_DISABLE("ACCOUNT_OUT_DISABLE"), PAYER_AMOUNT_EXCEED_DAILY_LIMIT_PAY(
            "PAYER_AMOUNT_EXCEED_DAILY_LIMIT_PAY"), PAYEE_AMOUNT_EXCEED_DAILY_LIMIT_PAY(
            "PAYEE_AMOUNT_EXCEED_DAILY_LIMIT_PAY"), PAYER_AMOUNT_EXCEED_MONTH_LIMIT_PAY(
            "PAYER_AMOUNT_EXCEED_MONTH_LIMIT_PAY"), PAYEE_AMOUNT_EXCEED_MONTH_LIMIT_PAY(
            "PAYEE_AMOUNT_EXCEED_MONTH_LIMIT_PAY"), PAYER_AMOUNT_EXCEED_YEAR_LIMIT_PAY(
            "PAYER_AMOUNT_EXCEED_YEAR_LIMIT_PAY"), PAYEE_AMOUNT_EXCEED_YEAR_LIMIT_PAY(
            "PAYEE_AMOUNT_EXCEED_YEAR_LIMIT_PAY"), MERCHANT_ACCOUNT_OUT_DISABLE("MERCHANT_ACCOUNT_OUT_DISABLE"), MERCHANT_ACCOUNT_IN_DISABLE(
            "MERCHANT_ACCOUNT_IN_DISABLE"), TRANS_FROZEN("TRANS_FROZEN"), TRANS_PAID("TRANS_PAID"), TRANS_CLOSED(
            "TRANS_CLOSED"), BUYER_NOT_CONSISTENT("BUYER_NOT_CONSISTENT"), SERVICE_INST_NOT_EXIST(
            "SERVICE_INST_NOT_EXIST"), FEE_PAYMENT_CONSULT_FAIL("FEE_PAYMENT_CONSULT_FAIL"), BALANCE_OVER_LIMIT(
            "BALANCE_OVER_LIMIT"), HYBRID_CHANNEL_NOT_AVAILABLE("HYBRID_CHANNEL_NOT_AVAILABLE"), ACCOUNT_BALANCE_QUERY_FAIL(
            "ACCOUNT_BALANCE_QUERY_FAIL"), BALANCE_ACCOUNT_STATUS_DISABLED("BALANCE_ACCOUNT_STATUS_DISABLED"), ADD_MONEY_WALLET_CONSULT_FAILED(
            "ADD_MONEY_WALLET_CONSULT_FAILED"), EMI_PROCESSING_FAILED("EMI_PROCESSING_FAILED"), PAYER_AMOUNT_EXCEED_DAILY_LIMIT_USER_DEFINED(
            "PAYER_AMOUNT_EXCEED_DAILY_LIMIT_USER_DEFINED"), PAYER_COUNT_EXCEED_DAILY_LIMIT_USER_DEFINED(
            "PAYER_COUNT_EXCEED_DAILY_LIMIT_USER_DEFINED"), PAYER_AMOUNT_EXCEED_MONTH_LIMIT_USER_DEFINED(
            "PAYER_AMOUNT_EXCEED_MONTH_LIMIT_USER_DEFINED"), PAYER_COUNT_EXCEED_MONTH_LIMIT_USER_DEFINED(
            "PAYER_COUNT_EXCEED_MONTH_LIMIT_USER_DEFINED"), PAYER_AMOUNT_EXCEED_MONTH_LIMIT_MIN_KYC(
            "PAYER_AMOUNT_EXCEED_MONTH_LIMIT_MIN_KYC"), INVALID_PAYMENT_DETAILS("INVALID_PAYMENT_DETAILS"), INVALID_REQUEST_TYPE(
            "INVALID_REQUEST_TYPE"), INVALID_TXN_AMOUNT("INVALID_TXN_AMOUNT"), INVALID_ORDER_ID("INVALID_ORDER_ID"), INVALID_CARD_NO(
            "INVALID_CARD_NO"), INVALID_SAVED_CARD_ID("INVALID_SAVED_CARD_ID"), INVALID_MONTH("INVALID_MONTH"), INVALID_YEAR(
            "INVALID_YEAR"), INVALID_CVV("INVALID_CVV"), INVALID_PAYMENTMODE("INVALID_PAYMENTMODE"), INVALID_PROMOCODE(
            "INVALID_PROMOCODE"), INVALID_CUST_ID("INVALID_CUST_ID"), INVALID_INDUSTRY_TYPE_ID(
            "INVALID_INDUSTRY_TYPE_ID"), INVALID_CARD_STORE_FLAG("INVALID_CARD_STORE_FLAG"), INVALID_CHANNEL(
            "INVALID_CHANNEL"), INVALID_PAYTM_ID("INVALID_PAYTM_ID"), INVALID_OTP("INVALID_OTP"), INVALID_MID(
            "INVALID_MID"), INVALID_TRANS_TYPE("INVALID_TRANS_TYPE"), INVALID_SUBS_START_DATE("INVALID_SUBS_START_DATE"), INVALID_SUBS_END_DATE(
            "INVALID_SUBS_END_DATE"), INVALID_MMID("INVALID_MMID"), INVALID_MOBILE_NUMBER("INVALID_MOBILE_NUMBER"), INVALID_PARAM(
            "INVALID_PARAM"), INVALID_CARD_TOKEN("INVALID_CARD_TOKEN"), INVALID_CC_BILL_NO("INVALID_CC_BILL_NO"), NATIVE_RETRY_COUNT_BREACHED(
            "NATIVE_RETRY_COUNT_BREACHED"), INVALID_CARD_NUMBER("INVALID_CARD_NUMBER"), INVALID_EXPIRY_DATE(
            "INVALID_EXPIRY_DATE"), TOKEN_NOT_GENERATD("TOKEN_NOT_GENERATD"), INCOMPLETE_CARD_INFORMATION(
            "INCOMPLETE_CARD_INFORMATION"), INVALID_JSON_DATA("INVALID_JSON_DATA"), INVALID_REQUEST_FORMAT(
            "INVALID_REQUEST_FORMAT"), INTERNAL_PROCESSING_ERROR("INTERNAL_PROCESSING_ERROR"), FAILURE("FAILURE"), SUCCESS(
            "SUCCESS"), SUCCESS_RESPONSE_CODE("SUCCESS_RESPONSE_CODE"), FGW_BANK_FORM_RETRIEVE_FAILED(
            "FGW_BANK_FORM_RETRIEVE_FAILED"), FGW_INVALID_VPA("FGW_INVALID_VPA"), LOYALTY_POINT_NOT_CONFIGURED(
            "LOYALTY_POINT_NOT_CONFIGURED"), MERCHANT_FAILURE_RESPONSE("MERCHANT_FAILURE_RESPONSE"), CORE_SESSION_EXPIRED_FAILURE(
            "CORE_SESSION_EXPIRED_FAILURE"), INVALID_CHECKSUM("INVALID_CHECKSUM"), MERCHANT_VELOCITY_LIMIT_BREACH(
            "MERCHANT_VELOCITY_LIMIT_BREACH"), INVALID_ORDER("INVALID_ORDER"), BALANCE_NOT_ENOUGH("BALANCE_NOT_ENOUGH"), APPLICATION_DOWN(
            "APPLICATION_DOWN"), BALANCE_NOT_ENOUGH_SUBS("BALANCE_NOT_ENOUGH_SUBS"), ORDER_CLOSE("ORDER_CLOSE"), REFUND_FAILED(
            "REFUND_FAILED"), REFUND_PENDING("REFUND_PENDING"), REFUND_SUCCESS("REFUND_SUCCESS"), NO_RECORD_FOUND(
            "NO_RECORD_FOUND"), SALE_PENDING_WITHOUT_BANKNAME("SALE_PENDING_WITHOUT_BANKNAME"), SALE_PENDING(
            "SALE_PENDING"), LINK_USER_CLOSED_RESPONSE_CODE("LINK_USER_CLOSED_RESPONSE_CODE"), PENNY_DROP_MID_NOT_CONFIGURED(
            "PENNY_DROP_MID_NOT_CONFIGURED"), PENNY_DROP_ACCOUNT_VERIFICATION_FAIL(
            "PENNY_DROP_ACCOUNT_VERIFICATION_FAIL"), PENNY_DROP_SERVICE_ERROR("PENNY_DROP_SERVICE_ERROR"), PENNY_DROP_ORDER_ID_CREATION_ERROR(
            "PENNY_DROP_ORDER_ID_CREATION_ERROR"), VPA_ACCOUNT_VERIFICATION_FAIL("VPA_ACCOUNT_VERIFICATION_FAIL"), VPA_SERVICE_ERROR(
            "VPA_SERVICE_ERROR"), CACHE_CARD_SERVICE_ERROR("CACHE_CARD_SERVICE_ERROR"), CACHE_CARD_INVALID_RESPONSE(
            "CACHE_CARD_INVALID_RESPONSE"), RISK_POLICY_CONSULT_SERVICE_ERROR("RISK_POLICY_CONSULT_SERVICE_ERROR"), ASYNC_RISK_POLICY_CONSULT_SERVICE_ERROR(
            "ASYNC_RISK_POLICY_CONSULT_SERVICE_ERROR"), RISK_CONSULT_VERIFICATION_FAIL("RISK_CONSULT_VERIFICATION_FAIL"), ASYNC_RISK_CONSULT_VERIFICATION_FAIL(
            "ASYNC_RISK_CONSULT_VERIFICATION_FAIL"), INVALID_REQUEST_PARAMETERS("INVALID_REQUEST_PARAMETERS"), KYB_NOT_PERMITTED(
            "KYB_NOT_PERMITTED"), KYB_NO_RELATION_FOUND("KYB_NO_RELATION_FOUND"), PAYMENT_OFFER_CHECKOUT_FAILURE(
            "PAYMENT_OFFER_CHECKOUT_FAILURE"), INVALID_SSO_TOKEN("INVALID_SSO_TOKEN"), PAY_MODES_ARE_BLANK_FOR_PROMO_CODE(
            "PAY_MODES_ARE_BLANK_FOR_PROMO_CODE"), GV_CONSENT_REQUIRED("GV_CONSENT_REQUIRED"), INVALID_ONECLICK_TXN_AMOUNT(
            "INVALID_ONECLICK_TXN_AMOUNT"), PREPAID_CARD_NOT_SUPPORTED("PREPAID_CARD_NOT_SUPPORTED"), PPI_LIMIT_PAYMODE_AMOUNT_BREACHED(
            "PPI_LIMIT_PAYMODE_AMOUNT_BREACHED"), FGW_PREFERRED_OTP_PAGE_BANK_FAILURE(
            "FGW_PREFERRED_OTP_PAGE_BANK_FAILURE"), FGW_PREFERRED_OTP_PAGE_MERCHANT_FAILURE(
            "FGW_PREFERRED_OTP_PAGE_MERCHANT_FAILURE"), ADD_MONEY_WALLET_LIMIT_BREACH("ADD_MONEY_WALLET_LIMIT_BREACH"), INVALID_TIP_AMOUNT(
            "INVALID_TIP_AMOUNT"), GENERATE_TOKEN_DETAIL_FAILURE("GENERATE_TOKEN_DETAIL_FAILURE"), COFT_SERVICE_ERROR(
            "COFT_SERVICE_ERROR"), MANDATORY_PARAM_MISSING("MANDATORY_PARAM_MISSING"), JWT_VALIDATION_FAILURE(
            "JWT_VALIDATION_FAILURE"), INVALID_TOKEN_INDEX_NUMBER("INVALID_TOKEN_INDEX_NUMBER"), COFT_CHANNEL_NOT_AVAILABLE(
            "COFT_CHANNEL_NOT_AVAILABLE"), AMOUNT_MISMATCH("AMOUNT_MISMATCH"), TXNID_MISMATCH("TXNID_MISMATCH"), EDC_LINK_BANK_OFFER_FAILURE(
            "EDC_LINK_BANK_OFFER_FAILURE"), EDC_LINK_BRAND_EMI_OFFER_FAILURE("EDC_LINK_BRAND_EMI_OFFER_FAILURE"), EDC_LINK_BANK_BRAND_CHECKOUT_FAILURE(
            "EDC_LINK_BANK_BRAND_CHECKOUT_FAILURE"), VALIDATION_API_FAILURE("VALIDATION_API_FAILURE"), WALLET_INACTIVE_FAILURE(
            "WALLET_INACTIVE_FAILURE"), UPI_USER_NOT_FOUND("UPI_USER_NOT_FOUND"), TOKEN_DETAIL_NOT_FOUND(
            "TOKEN_DETAIL_NOT_FOUND"), INVALID_REQUEST_ID("INVALID_REQUEST_ID"), INCORRECT_DETAILS_PASSED(
            "INCORRECT_DETAILS_PASSED"), SIGNATURE_VALIDATION_FAILURE("SIGNATURE_VALIDATION_FAILURE"),CHECKSUM_VALIDATION_FAILURE(
            "CHECKSUM_VALIDATION_FAILURE"), SIGNATURE_TYPE_MISSING("SIGNATURE_TYPE_MISSING"),HEAD_IS_MISSING("HEAD_IS_MISSING"),PAR_NOT_FOUND(
            "PAR_NOT_FOUND"), CARD_SCHEME_IS_NOT_SUPPORTED("CARD_SCHEME_IS_NOT_SUPPORTED"),DB_ERROR("DB_ERROR"),
            EDC_LINK_VALIDATE_VELOCITY_API_FAILURE("EDC_LINK_VALIDATE_VELOCITY_API_FAILURE"),
            INVALID_UPI_NUMBER("INVALID_UPI_NUMBER"),LINK_PAYMENT_CONSULT_FAILURE("LINK_PAYMENT_CONSULT_FAILURE"),
            LINK_PAYMENT_IN_PROCESS("LINK_PAYMENT_IN_PROCESS"),
            LINK_PAYMENT_ALREADY_PROCESSED("LINK_PAYMENT_ALREADY_PROCESSED"),
            TXN_AMT_AND_PAID_AMT_EXCEEDS_TOTAL_PAYMENT_AMT("TXN_AMT_AND_PAID_AMT_EXCEEDS_TOTAL_PAYMENT_AMT"),
            TOTAL_PAYMENT_AMOUNT_LIMIT_REACHED("TOTAL_PAYMENT_AMOUNT_LIMIT_REACHED"),
            DIGITAL_CARD_EXPIRED("DIGITAL_CARD_EXPIRED"),
            DIGITAL_TOKEN_EXPIRED("DIGITAL_TOKEN_EXPIRED"),
            FAILED_SUSPENDED_TOKEN("FAILED_SUSPENDED_TOKEN"),
            FAILED_RETRY_INIT("FAILED_RETRY_INIT"),
            FAILURE_FROM_CARD_NETWORK("FAILURE_FROM_CARD_NETWORK"),
            ERROR_WHILE_GENERATING_TOKEN_FROM_CARD_NETWORK("ERROR_WHILE_GENERATING_TOKEN_FROM_CARD_NETWORK"),
            CARD_NOT_ELIGIBLE("CARD_NOT_ELIGIBLE"),
            CARD_VERIFICATION_FAILED_BY_NETWORK("CARD_VERIFICATION_FAILED_BY_NETWORK"),
            CARD_NOT_ALLOWED_BY_NETWORK("CARD_NOT_ALLOWED_BY_NETWORK"),
            TRID_NOT_CONFIGURED("TRID_NOT_CONFIGURED"),
            BAD_REQUEST("BAD_REQUEST"),INVALID_WALLET_2FA_PASSCODE("INVALID_WALLET_2FA_PASSCODE");


    private String systemRespCode;

    public String getSystemRespCode() {
        return systemRespCode;
    }

    SystemResponseCode(String systemRespCode) {
        this.systemRespCode = systemRespCode;
    }
}
